name: TemporalClusterNet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.2
  - earthengine-api=0.1.393
  - earthpy=0.9.4
  - folium=0.14.0
  - geemap=0.32.0
  - geopandas=0.14.2
  - matplotlib=3.8.0
  - numpy=1.26.4
  - pandas=2.2.1
  - rasterio=1.3.9
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - shapely=2.0.3
  - xgboost=2.0.3
  - progressbar2=4.4.2 # Not sure if this is the right version
  - spams-bin=2.6.10 # Not sure if this is the right version
  - networkx=3.1 # Not sure if this is the right version
  # - pomegranate=1.0.0 # Not sure if this is the right version
  - pip # pip=23.4.0 23.3.1
  - pip:
      - tensorflow==2.16.1
      - pysan==0.22.1 # Not sure if this is the right version
      - git+https://github.com/jacobkrantz/Simple-HOHMM.git#egg=simplehohmm